[build]
publish = "dist"
command = "npm run build"

[[redirects]]
from = "/about.html"
to = "/tr/hakkimizda.html"
status = 301

[[redirects]]
from = "/contact.html"
to = "/tr/iletisim.html"
status = 301

[[redirects]]
from = "/privacy.html"
to = "/tr/gizlilik-politikasi.html"
status = 301

[[redirects]]
from = "/terms.html"
to = "/tr/kullanim-kosullari.html"
status = 301

[[redirects]]
from = "/FAQ.html"
to = "/tr/sik-sorulan-sorular.html"
status = 301

[[redirects]]
from = "/team.html"
to = "/tr/ekibimiz.html"
status = 301

[[redirects]]
from = "/blog.html"
to = "/tr/blog.html"
status = 301

[[redirects]]
from = "/blog-single.html"
to = "/tr/blog-yazisi.html"
status = 301

[[redirects]]
from = "/career.html"
to = "/tr/kariyer.html"
status = 301

[[redirects]]
from = "/comming-soon.html"
to = "/tr/yakinda.html"
status = 301

[[redirects]]
from = "/homepage-2.html"
to = "/tr/urun-tanitimi.html"
status = 301

[[redirects]]
from = "/homepage-3.html"
to = "/tr/surec-yonetimi.html"
status = 301

[[redirects]]
from = "/privacy-policy_ex.html"
to = "/tr/privacy-policy_ex.html"
status = 301

[[redirects]]
from = "/sign-in.html"
to = "/tr/giris.html"
status = 301

[[redirects]]
from = "/sign-up.html"
to = "/tr/kayit.html"
status = 301

[[redirects]]
from = "/404.html"
to = "/tr/404.html"
status = 301

[[redirects]]
from = "/tr/about.html"
to = "/tr/hakkimizda.html"
status = 301

[[redirects]]
from = "/tr/contact.html"
to = "/tr/iletisim.html"
status = 301

[[redirects]]
from = "/tr/privacy.html"
to = "/tr/gizlilik-politikasi.html"
status = 301

[[redirects]]
from = "/tr/terms.html"
to = "/tr/kullanim-kosullari.html"
status = 301

[[redirects]]
from = "/tr/FAQ.html"
to = "/tr/sik-sorulan-sorular.html"
status = 301

[[redirects]]
from = "/tr/team.html"
to = "/tr/ekibimiz.html"
status = 301

[[redirects]]
from = "/tr/blog-single.html"
to = "/tr/blog-yazisi.html"
status = 301

[[redirects]]
from = "/tr/career.html"
to = "/tr/kariyer.html"
status = 301

[[redirects]]
from = "/tr/comming-soon.html"
to = "/tr/yakinda.html"
status = 301

[[redirects]]
from = "/tr/homepage-2.html"
to = "/tr/urun-tanitimi.html"
status = 301

[[redirects]]
from = "/tr/homepage-3.html"
to = "/tr/surec-yonetimi.html"
status = 301

[[redirects]]
from = "/tr/sign-in.html"
to = "/tr/giris.html"
status = 301

[[redirects]]
from = "/tr/sign-up.html"
to = "/tr/kayit.html"
status = 301

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
